//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlQueryStress.DbProviders.Tests.QueryPlans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryPlanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryPlanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlQueryStress.DbProviders.Tests.QueryPlans.QueryPlanResources", typeof(QueryPlanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ShowPlanXML xmlns=&quot;http://schemas.microsoft.com/sqlserver/2004/07/showplan&quot; Version=&quot;1.6&quot; Build=&quot;14.0.2027.2&quot;&gt;
        ///  &lt;BatchSequence&gt;
        ///    &lt;Batch&gt;
        ///      &lt;Statements&gt;
        ///        &lt;StmtSimple StatementText=&quot;SELECT&amp;#xD;&amp;#xA;&amp;#x9;ProductID,&amp;#xD;&amp;#xA;&amp;#x9;DATEFROMPARTS(YEAR(soh.OrderDate), MONTH(soh.OrderDate), 01) [Date],&amp;#xD;&amp;#xA;&amp;#x9;SUM(UnitPrice * OrderQty) [TotalSales]&amp;#xD;&amp;#xA;FROM&amp;#xD;&amp;#xA;&amp;#x9;[Sales].[SalesOrderDetail] sod&amp;#xD;&amp;#xA;&amp;#x9;JOIN [Sales].[SalesOrderHeader] soh ON soh.SalesOrderID = sod.SalesOrde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventureWorks_MonthlyProductSales {
            get {
                return ResourceManager.GetString("AdventureWorks_MonthlyProductSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ShowPlanXML xmlns=&quot;http://schemas.microsoft.com/sqlserver/2004/07/showplan&quot; Version=&quot;1.6&quot; Build=&quot;14.0.2027.2&quot;&gt;
        ///  &lt;BatchSequence&gt;
        ///    &lt;Batch&gt;
        ///      &lt;Statements&gt;
        ///        &lt;StmtSimple StatementText=&quot;SELECT DISTINCT pp.LastName, pp.FirstName &amp;#xD;&amp;#xA;FROM Person.Person pp JOIN HumanResources.Employee e&amp;#xD;&amp;#xA;ON e.BusinessEntityID = pp.BusinessEntityID WHERE pp.BusinessEntityID IN &amp;#xD;&amp;#xA;(SELECT SalesPersonID &amp;#xD;&amp;#xA;FROM Sales.SalesOrderHeader&amp;#xD;&amp;#xA;WHERE SalesOrderID IN &amp;#xD;&amp;#xA;(SELECT SalesO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventureWorks_SalesPersonByProduct {
            get {
                return ResourceManager.GetString("AdventureWorks_SalesPersonByProduct", resourceCulture);
            }
        }
    }
}
